// Chart Option
const options = {
    chart: {
        height: 600,
        width: '100%',
        type: 'bar',
        background: ' rgba(49, 24, 131, 0.9)',
        foreColor: '#f4f4f4'
    },

    series: [{
            name: 'visits',
            data: [
            4406,
            3939,
            2910,
            1701,
            1612,
//            343,
//            342,
//            242,
//            236,
//            235,
//            224,
//            172,
//            172,
//            170,
//            115,
//            113,
//            107,
//            91,
//            72,
//            66,
//            60,
//            58,
//            57,
//            56,
//            56,
//            55,
//            54,
//            47,
//            47,
//            44,
//            39,
//            35,
//            34,
//            31,
//            26,
//            25,
//            25,
//            23,
//            23,
//            22,
//            20,
//            19,
//            19,
//            18,
//            16,
//            16,
//            15,
//            15,
//            11,
//            10,
//            9,
//            8,
//            8,
//            7,
//            7,
//            7,
//            7,
//            7,
//            7,
//            7,
//            3,
//            2,
//            1,
//            0,
              ]
            },
             {
            name: 'Escalations',
          data: [
                108,
                225,
                160,
                103,
                73,
//                2,
//                1,
//                2,
//                1,
//                8,
//                5,
//                0,
//                8,
//                4,
//                1,
//                1,
//                2,
//                1,
//                0,
//                7,
//                0,
//                0,
//                3,
//                0,
//                0,
//                0,
//                0,
//                0,
//                1,
//                1,
//                4,
//                1,
//                0,
//                1,
//                0,
//                0,
//                0,
//                0,
//                0,
//                1,
//                0,
//                0,
//                1,
//                0,
//                0,
//                0,
//                2,
//                0,
//                0,
//                0,
//                0,
//                0,
//                0,
//                0,
//                1,
//                0,
//                0,
//                0,
//                0,
//                0,
//                0,
//                0,
//                0,
//                0,
              ]
           },
              {
            name: 'Helpful',
            data: [
                37.1,
                34.1,
                48.3,
                28.6,
                38.5,
//                28.6,
//                50.0,
//                90.9,
//                88.9,
//                77.8,
//                50.0,
//                0.0,
//                25.0,
//                33.3,
//                0.0,
//                50.0,
//                100.0,
//                0.0,
//                0.0,
//                50.0,
//                100.0,
//                0.0,
//                0.0,
//                0.0,
//                80.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                66.7,
//                0.0,
//                0.0,
//                0.0,
//                50.0,
//                0.0,
//                100.0,
//                0.0,
//                100.0,
//                50.0,
//                0.0,
//                0.0,
//                0.0,
//                50.0,
//                100.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                100.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
//                0.0,
              ]
           }
         ],

    xaxis: {
        categories: [
            'Changing Your Booking',
            'Lost Flybe Booking Reference Number',
            'Choosing to Cancel a Flight',
            'Lost Receipt (Confirmation of booking)',
            'Name Changes',
//            'Ticket Types Explained',
//            'Charges for Changing a Booking',
//            'e-Tickets',
//            'Will I Receive Tickets?',
//            'Cancelling One Flight in a Booking',
//            'How To Book a Flight',
//            'Off-Shore Workers & Ticket Changes',
//            'Missing Your Flight',
//            'I Have Booked the Wrong Flight',
//            'What Seating Options Are Available?',
//            'Just Fly Flex',
//            'Seating Everyone on a Booking Together',
//            'Changing the Email Address for Your Booking or Account',
//            'Connecting Flights',
//            'Taxes and Charges Included in Bookings',
//            'Fly Early',
//            'Restrictions to Changing a Booking',
//            'Asked to Move Seats On Board',
//            'Booking an Infant Before Birth',
//            'Adding Passengers to Existing Bookings',
//            'Payment Options on Flybe.com',
//            'Who is Operating My Flight?',
//            'Minimum Age for Newborn Babies on Flybe Flights',
//            'Confirmation of Booking With a Travel Agent or Third Party',
//            'Making Changes After Checking In',
//            'What can I do if I have accidentally double-booked?',
//            'Booking an Extra/Comfort Seat',
//            'Changing One Flight Only of a Return Booking',
//            'Flybe Travel Insurance Coverage',
//            'Can I make a booking online to fly out from one airport and return from ano',
//            'Upgrading Your Ticket Type',
//            'Flybe Gift Vouchers',
//            'Booking a Flight for Someone Else',
//            'Reversing Changes Made to a Booking',
//            'What Happens Once a Booking Has Been Made Online?',
//            'Flybe.com & App Changes',
//            'Adding a Return Flight to a One-Way Booking',
//            'Booking Using an Air Discount Scheme (ADS) Card',
//            'Changing a Booking for One Person Only',
//            'Transferring Pre-Booked Seats When Changing Flights',
//            'Reduced Fares',
//            'Additional Charges Levied by Flybe',
//            'Booking Without Travel Insurance',
//            'Air Discount Scheme Information',
//            'Is an Email Address Required to Book a Flight?',
//            'Changing a Booking Not Made Directly by Flybe',
//            'Air Discount Scheme (ADS) Card Issues',
//            'PayPal Currency Options',
//            'Announcements On Board',
//            'Can I use multiple payment cards to pay for one booking?',
//            'Forgotten PayPal Password or Email Address',
//            'Business & Corporate Bookings',
//            'Travelling With Chickenpox',
//            'Credit & Debit Card Security Number',
//            'PayPal Payment Issues',
//            'PayPal Payments',
//            'Setting Up a PayPal Account',
//            'PayPal Handling Charges',
//            'What is a Sector?',
        ]
    },
    plotOptions:{
        bar:{
            horizontal: false
        }
    },
//    fill:{
//        colors: ['#f44336']
//    },
    dataLabels:{
        enabled: false
    },
    title:{
        text: 'Answer Effectiveness (Bookings)',
        align: 'center',
        margin: 20,
        offsetY: 20,
        style: {
            fontSize: '25px'
      }
    }
}
// Init Chart
const chart = new ApexCharts(document.querySelector("#chart"), options);



// Render chart
chart.render();

//Event Method Example
document.querySelector('button').addEventListener('click', () => chart.updateOptions({
     plotOptions:{
        bar:{
            horizontal: true
        }
    },
  })
)
